### ISSUE TITLE
Error trying to compile in Ubuntu 20.04 using WSL

### ISSUE THREAD

**Issue by Jaantheman** [jdah/jdh-8#26]
Ok so when I was trying to compile the code I ran into this error
**Error:**
emu/emu.c:12:14: fatal error: 'readline/readline.h' file not found
    #include <readline/readline.h>
It's kind of obvious the file is missing or not found(said in the error) But where is this file located because it was the only error I got.
**Here is the full Makefile logs V**
(my user and pc)~/jdh-8$ make
mkdir -p bin
clang -o emu/kb.o -c emu/kb.c -std=c11 -O2 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wno-pointer-arith -Wno-unused-parameter -Wno-gnu-zero-variadic-macro-arguments
clang -o emu/emu.o -c emu/emu.c -std=c11 -O2 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wno-pointer-arith -Wno-unused-parameter -Wno-gnu-zero-variadic-macro-arguments
emu/emu.c:12:14: fatal error: 'readline/readline.h' file not found
    #include <readline/readline.h>
             ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:77: emu/emu.o] Error 1

So where can I find this readline.h file. Just to clarify I am using WSL Ubuntu 20.04. By the way this was the only error I have encountered so far.

**Comment by Jaantheman** [comment]
I don't know if readline.h is apart of SDL2 but it looks like no because this imported perfectly fine since there was no other error:
#include <readline/history.h>

**Comment by hdfsyu** [comment]
@Jaantheman In the terminal type this: sudo apt install readline-dev
